
/******************************************************************************
 *
 *  This file is part of meryl-utility, a collection of miscellaneous code
 *  used by Meryl, Canu and others.
 *
 *  This software is based on:
 *    'Canu' v2.0              (https://github.com/marbl/canu)
 *  which is based on:
 *    'Celera Assembler' r4587 (http://wgs-assembler.sourceforge.net)
 *    the 'kmer package' r1994 (http://kmer.sourceforge.net)
 *
 *  Except as indicated otherwise, this is a 'United States Government Work',
 *  and is released in the public domain.
 *
 *  File 'README.licenses' in the root directory of this distribution
 *  contains full conditions and disclaimers.
 */

#ifndef MERYLUTIL_BITS_H
#define MERYLUTIL_BITS_H

#include "bits/fibonacci-v1.H"
#include "bits/bits-v1.H"

#include "bits/murmur-v1.H"

#include "bits/hexDump-v1.H"

#include "bits/bitArray-v1.H"
#include "bits/wordArray-v1.H"

#include "bits/stuffedBits-v1.H"

#endif  //  MERYLUTIL_BITS_H
