
/******************************************************************************
 *
 *  This file is part of meryl-utility, a collection of miscellaneous code
 *  used by Meryl, Canu and others.
 *
 *  This software is based on:
 *    'Canu' v2.0              (https://github.com/marbl/canu)
 *  which is based on:
 *    'Celera Assembler' r4587 (http://wgs-assembler.sourceforge.net)
 *    the 'kmer package' r1994 (http://kmer.sourceforge.net)
 *
 *  Except as indicated otherwise, this is a 'United States Government Work',
 *  and is released in the public domain.
 *
 *  File 'README.licenses' in the root directory of this distribution
 *  contains full conditions and disclaimers.
 */

#ifndef MERYLUTIL_SYSTEM_H
#define MERYLUTIL_SYSTEM_H

#include "system/system-v1.H"
#include "system/runtime-v1.H"
#include "system/ansi-escape-v1.H"

#include "system/time-v1.H"

#include "system/cpuIdent-v1.H"

#include "system/logging-v1.H"

#include "system/speedCounter-v1.H"

#include "system/sweatShop-v1.H"

#endif  //  MERYLUTIL_SYSTEM_H
